### ISSUE TITLE
Floating point exception / integer division by zero

### ISSUE THREAD

**Issue by tdd11235813** [clMathLibraries/clFFT#159]
Hi,
when using certain 2D transforms, a floating point exception occurs (both CPU and GPU), which actually seems to be an integer division by zero.
Some 2D examples (with code from pull request #158 ):
```
x            y   Result
65536       64   OK
131072       2   FAIL
2       131072   OK
131072      64   FAIL
131072     128   FAIL
128     131072   FAIL
1048576     64   OK
```
This also happens for clFFT-client -x x -y y -p 10
```
x            y   Result
65536       64   OK
131072      64   FAIL
1048576     64   OK
1048576      2   FAIL
```
_Environment_
- cuda/7.5.18
- opencl/1.2-4.4.0.117
- gcc/5.3.0
- clFFT/2.12.0 and clFFT/2.12.1
- RHEL 6.7
- GPU K20X and Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz
_Stacktrace_
```
Program received signal SIGFPE, Arithmetic exception.
0x00007ffff7d7d228 in StockhamGenerator::Kernel<(StockhamGenerator::Precision)0>::GenerateKernel (this=this@entry=0x7fffffff8020, str=..., Dev_ID=0x6bb928)
    at clFFT/src/library/generator.stockham.cpp:4164
4164                                            str += "\n\tfor(uint t=0; t<"; str += SztToStr(blockWidth/(blockWGS/workGroupSizePerTrans));
(gdb) bt
#0  0x00007ffff7d7d228 in StockhamGenerator::Kernel<(StockhamGenerator::Precision)0>::GenerateKernel (this=this@entry=0x7fffffff8020, str=..., Dev_ID=0x6bb928)
    at clFFT/src/library/generator.stockham.cpp:4164
#1  0x00007ffff7d587bd in FFTGeneratedStockhamAction::generateKernel (this=this@entry=0x217c140, fftRepo=..., commQueueFFT=commQueueFFT@entry=0x1cf0668)
    at clFFT/src/library/generator.stockham.cpp:4695
#2  0x00007ffff7d58d1a in FFTGeneratedStockhamAction::FFTGeneratedStockhamAction (this=0x217c140, plHandle=3, plan=0x217bcc0, queue=0x1cf0668, err=@0x7fffffff838c: CLFFT_SUCCESS)
    at clFFT/src/library/generator.stockham.cpp:46
#3  0x00007ffff7d40f18 in selectAction (fftPlan=fftPlan@entry=0x217bcc0, action=@0x217beb8: 0x0, commQueueFFT=commQueueFFT@entry=0x7fffffffbac8) at clFFT/src/library/plan.cpp:411
#4  0x00007ffff7d44583 in clfftBakePlan (plHandle=3, numQueues=numQueues@entry=1, commQueueFFT=commQueueFFT@entry=0x7fffffffbac8, pfn_notify=pfn_notify@entry=0x0, user_data=user_data@entry=0x0)
    at clFFT/src/library/plan.cpp:4537
#5  0x00007ffff7d4a144 in clfftBakePlan (plHandle=<optimized out>, numQueues=numQueues@entry=1, commQueueFFT=commQueueFFT@entry=0x7fffffffbac8, pfn_notify=pfn_notify@entry=0x0, 
    user_data=user_data@entry=0x0) at clFFT/src/library/plan.cpp:2110
#6  0x00007ffff7d47e13 in clfftBakePlan (plHandle=<optimized out>, numQueues=numQueues@entry=1, commQueueFFT=commQueueFFT@entry=0x7fffffffbac8, pfn_notify=pfn_notify@entry=0x0, 
    user_data=user_data@entry=0x0) at clFFT/src/library/plan.cpp:2552
#7  0x000000000042826a in transform<float> (lengths=lengths@entry=0x7fffffffc380, inStrides=inStrides@entry=0x7fffffffc3a0, outStrides=outStrides@entry=0x7fffffffc3c0, batch_size=1, 
    in_layout=CLFFT_COMPLEX_INTERLEAVED, out_layout=CLFFT_COMPLEX_INTERLEAVED, place=CLFFT_INPLACE, precision=CLFFT_SINGLE, dir=CLFFT_FORWARD, deviceType=4294967295, deviceId=0, platformId=0, 
    printInfo=false, command_queue_flags=0, profile_count=1, setupData=...) at clFFT/src/client/client.cpp:415
#8  0x0000000000423f6b in main (argc=5, argv=0x7fffffffc9f8) at clFFT/src/client/client.cpp:1031

(gdb) p blockWGS
$4 = 3
(gdb) p blockWidth
$5 = 512
(gdb) p workGroupSizePerTrans
$6 = 64
```
So the denominator becomes zero as `blockWGS/workGroupSizePerTrans`. Haven't digged deeper, but there are probably more code lines being affected by this. 
I hope you can help or did I oversee something?
Best Regards

**Comment by bragadeesh** [comment]
I made a fix for this in the develop branch; can you check with tip of develop branch; thanks
